[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26068ad086a743873f38c31b12c8cacd299f140f"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "c21fe858022b22b052c781391ab1ccbc2813b48caf1dfd344646603ae13c7a78"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe101e459ccecbb2002f974835fb6c7c06447538"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "c6d8eaaf7e448f276c097b5946002e594a584682be7b3a7acbc98caa12b851f3"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e761bf99c6500fe42080c4a5cbd8ce2a1e532e24"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "81f7d45943a085e5f86992fe4dec1841cc63d35d06bb958014fe8d8e7bc422fe"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ecf0b5e46c65d4e059d81079bc39fecd739bf610"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "20d0eac666d4f36adc42b7816c412356fed8fc25b3828f36f7e0c9dd3b6ebd30"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[assimp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4debaf465be6ab3546ce902adc272150230fac30"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "e350ec6b6dd8b383573256057088823d0bb6f92ce13246471b63f30ec801749f"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[assimp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cb46d8519a872f49d972c1beaebb5d1c940304b"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "8ab7162ee4880980cabd93e68e78e1eb4032a6d39ac8f94af7c486654e25103c"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "788b008e041eeae9f1a13a41381d3a6d73f7f62b"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "ec2e979220ebdd7b7e72aacaeb678c7fdb69c9af330c8efb390e00c1487f6c35"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.i686-linux-gnu-cxx03.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f61685cd6a49437be15b4b961aa798b87a445246"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "4218b70bd7e86b4d90622d8bbbbb61f3d43ff8370402dd67fa605e9aaec4011c"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.i686-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b3ea3cb578cb002f9a6ff7399a14f2c5f42e1cd"
os = "windows"

    [[assimp.download]]
    sha256 = "547b8e8555fb778952796a656e5c1095d84de4e8df953307aeaae295cf2a2af2"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "536c3a97c3b524c62ceb96f2c8157fb7b0869e48"
os = "windows"

    [[assimp.download]]
    sha256 = "a39a60baada18e9a17c53a60e99cbb4eb465b7337aacc5237100c34e19f68aa5"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[assimp]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8172ebe365e5ffeba8c1983729c94a4eb49cbe38"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "39da5e7c7c2965f2d0e3a6bf43766dd7089bf3df43ea8fffa45ed4ea339eab91"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[assimp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b880513123345cea41d619d2e108ffec53edfc9a"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "13e6d8ffc1d160777dbe2eeb86383ac97a91ee4c54108f56351e18a595a43e22"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
git-tree-sha1 = "d3a8d47f21250abb45dade52c12b277c1dfe9c2a"
os = "macos"

    [[assimp.download]]
    sha256 = "d6fea73012376393f823397e7cc46109c44d6f066c0083c26ab0c145cb35ce61"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.x86_64-apple-darwin.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02785a562ce4818e3d98c00d143008705ac0083c"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "df30684df5968a4535b54182383ea6dc6147e93dd4d650560614de4fc942e7be"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "630beaf30deb713222a41abe44cb057abe1e2e13"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "e716f3bf7a63cd581cbeb344eaa19d8d7d0f15a1dbd64b96c922f95a1f1eb5d1"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "68c762277d2a0a75acadccda0e6169ed71f9b20e"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "b8a648dcab76713d86107732678dabf13027d8bd91c47d5f222c5d591b97dfa9"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35a18f583415c3926f14c32675a213175571d5fc"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "a5d3202c22475ed8de10ef2c5f2d0fc24d245ea22133e4811c6f2913c0ab1934"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
git-tree-sha1 = "b43f82ebdd4cd51823455c7a29b33ec64cdae6ac"
os = "freebsd"

    [[assimp.download]]
    sha256 = "63655994de84eddbbb7c602305a4c3b690056eae15ae7059c203a5d9880e0ab3"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.x86_64-unknown-freebsd.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b2965cb29a608aff08555508179c3c3d9ffc67a0"
os = "windows"

    [[assimp.download]]
    sha256 = "a86c5c336e165d07d22cc17f5851239a3948b22509456e9000c6c03741a3d82a"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cf436502dbbb7e246f8b0bc8d4e6def6d872842"
os = "windows"

    [[assimp.download]]
    sha256 = "319a9413d2e1ab30c6ed2a83d239b0390c6be62f8034253e53ec0356a19b6875"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+2/assimp.v5.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
