[[assimp]]
arch = "aarch64"
git-tree-sha1 = "6cc218b2013ce6f24a87dce4f62ba79d6c66edce"
os = "macos"

    [[assimp.download]]
    sha256 = "94c99f0ae5abe30f33ac29bdee8ed98d9535c1508787e955b59e8173afeb41b7"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.aarch64-apple-darwin.tar.gz"
[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0450159314981e3c620ee12a9335a18be0fde481"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "15d3956417e268d08587df6feb27f92720218fd1e488e471d5ff723a1a76da5b"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.aarch64-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edb68e6ca5074c65d15920c162666d228d3bbdf4"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "b265857b3513cda1879f72cb42daa2354bec4073ed69e937caa30e5db303315c"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.aarch64-linux-musl-cxx11.tar.gz"
[[assimp]]
arch = "aarch64"
git-tree-sha1 = "58e06defa8f9b603b16c794307d7b2b3ec6cfafb"
os = "freebsd"

    [[assimp.download]]
    sha256 = "a84a877cd5a0e6d8404b31ed6479a882d7a6ce0f1adc46934eae661ce93bd63d"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.aarch64-unknown-freebsd.tar.gz"
[[assimp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcf1d0888738e45bdabec94c06763fd0c619cc71"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "af9ba58ccfc783984b5619d8cf2bb8306baef1ef3576d4514764d719acc38581"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[assimp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5dbfdc00790e53705b2bb97a943e1df015431430"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "13ef10d6814c569607ccbf653f77a8f82468918b98960d0ae84510f7625730c0"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[assimp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e28c827f7a8efdc1a30ef3901436a105a9a055ed"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "8f0db48d9394b4416c350e552ff5d8a9301fc3e4393b143e5407e54f1f202c80"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[assimp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c65207b2d9cd930c47c2bba56bbfe8d74371644a"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "c837cfc1476a9da4b7edc0f78bb205083695b1058f0159ff7a3b0c8023a42a66"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "730efcec15551337107b563fd1b4a98abacb7fff"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "9288cded6786c1aebf108959b12b8fd87efa94f2cdc8d0611a5675111b632168"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.i686-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "405bf296239b2fc810ffe4fa3b82b2811d55fb4a"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "e382b44aee09a3e0d8751cd7cfdf50a911cb72219f6e42dd77a5758371aaf1ec"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.i686-linux-musl-cxx11.tar.gz"
[[assimp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5b743ccc27bef4e08b01c14a6005d2e32890445c"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "273118e1d0208387163368d7d0f953bdeea2a2d4d647788c147dd1fc8dc6ca9e"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e11f75a70658b977bb5c175af754c1d52d43ee12"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "8a0d445d7f4aa58bca206973e2b224285b57631bdcdb9eb32c1101d62e78fc86"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.riscv64-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
git-tree-sha1 = "e1d920747eade3b0ebdae3653b2e5e1256b2dfed"
os = "macos"

    [[assimp.download]]
    sha256 = "5c72f60de062be4dd03aec4cea6e8d5ca4cd97d6cceca7c244ad7cb987e596f0"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.x86_64-apple-darwin.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a078e8f6141927b0cc0dc18117f0f2876de55f76"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "549f76a61fbcf4030534427462c0f4e79ab724d39453ba78ee8ab3299cdb301a"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.x86_64-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f24a2d247b403f908f4951b08d0dc72cbe2eb0cd"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "e59da85cbe80a64eafd96a9435d190d51fc248044fbeb0bb32524df5ff76949a"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.x86_64-linux-musl-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
git-tree-sha1 = "9d7c5ff2466cd4c1f2c54fb64c068c90599e9feb"
os = "freebsd"

    [[assimp.download]]
    sha256 = "54a0c605abb6684015ab8db14a57e7aac97748adb1b36fdc34ec6069297ed81d"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+1/assimp.v6.0.4.x86_64-unknown-freebsd.tar.gz"
