[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2c4b272bd31408d3ca310806bc51add6e2de11f0"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "4f8f01d5eca217feb8c505ce55c93673ec3348a68c9b8a6a736dc776e48e2fc3"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "668b472c385225ac160dc05840fd92b8903510c2"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "95ebdef4c7370e177c1566415f01d95896eea16c9a249f9b069ca87d9e73fbb1"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1669f74603089761bb40a27f18765050b6938849"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "ca7bca54530d78d72e1a0248c64d5d0dd9acbe8d4f17c6888bcdc3a3a5ea8d26"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "634dbbd2471a007f111772a3d4f443af9a83a839"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "55bf5135186e59ad5de1542cc5147b60650c4f26fa8cbf4e80e8e354727b8e46"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[assimp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da0492d7fac447203b7fb2c230c088f7c6f748b3"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "180d8467d884b5a0dd30d02394d1bd2f04b569a10955f03a707cca8bddd961ac"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[assimp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22b7a1afa758c1da5d31c4aebd1e78e7db8b62e6"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "5b4aa9f9d4ac06cc32aeadad5cb2563414e8cde4b1a68c4eb3810bd76d074a6c"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e56daccc0eb751b53a6f6f90fb947c6d59ff2f25"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "4765ae91a1d143d317f6cb6dc0cd3b7e6e8b7da6fb84d24799ffcf6b7e7c79e4"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.i686-linux-gnu-cxx03.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d6e3dd23f47ceb5ac2e1e2146f45b91d2b25868"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "fc93d7a6c5e4cdeacbdca03796c70ca591a61dbc92b82c7114824ce0910b00b3"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.i686-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e69e8627989d8b3cfde94b977c2e671a4d3f8e9d"
os = "windows"

    [[assimp.download]]
    sha256 = "9c5bdcfde0821d6d3ffb3a5fc26c5c2bf52bf3d3af6f173d13b1e8b792ec60c9"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7606d35ac06a180d66690c838518c41063627ed"
os = "windows"

    [[assimp.download]]
    sha256 = "de12596fdbfd2c0697fc94b57312f209deaab4efeb09080b8f941bde31b25343"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[assimp]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f97d105ac83cc634c14c8629d1461d252ef14abc"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "f9b010e3a164d3fb958979cd11ee3168f71f80b03a1b7b6c8aa3d62301260e0e"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[assimp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d875955cfedb1dfabac479c718ae02623cef1ca3"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "bf274edba5e1e9d263b3ec2ed088ebadd6021cc1f794328ebd028db2b89e0edd"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
git-tree-sha1 = "8f0fc38683db01be19448d43bfd3f1d0a6d8bde0"
os = "macos"

    [[assimp.download]]
    sha256 = "fca89ade8dcf7abc177a9aad27878161c49ce539f89f9aa7e0db9df95ec1cafe"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.x86_64-apple-darwin.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c4ba0fcfe43e3d26a7c994027c23676b3c4b28ae"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "3af7fa2af8e93794aee1a2cd807d42856d8997cbbe1c3542045eb49b38873328"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02f2ef77c774fd2d2ea586fdf9f171dc132f179a"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "1f48848b907102358ab7a4c1907c4930e575cec27e205f1dd9067d130af9359b"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "084a8c0d7a80dee8ba09c4108448c5292e8d267c"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "4e7354fd44042ec30d27163487dc13f29cf9e2f68031aac4597df07f0878a435"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "85a2abab6d0cd475267464698836be81456b642c"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "7a9e7c834b9f1ce178a0d4410b376c5a118e856d568ab90266445c6b4f834293"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
git-tree-sha1 = "3f786653c5661d79321d1954a246c506f2e897b8"
os = "freebsd"

    [[assimp.download]]
    sha256 = "3bf75c2284b466d8ee9a7212f89021a3b2c944eb038253921481ffe851418e9e"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.x86_64-unknown-freebsd.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ba84cffc1dab5205ce63414abaea6f1b306f59a"
os = "windows"

    [[assimp.download]]
    sha256 = "dada0ab2f45def7a643bdc8dd9e7ead5eb1a562b8096cb77fa28d6b122eeba74"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e6e7910ebbf2a370871ee2a9b408b05a78f7022"
os = "windows"

    [[assimp.download]]
    sha256 = "4854dc542566ff3644edf12fb9ecb803cffc8acd1ced77206033322586202cd2"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v5.0.1+1/assimp.v5.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
