[[assimp]]
arch = "aarch64"
git-tree-sha1 = "7a9dd6a4c38ecfbb422bf95e916cb600216429e9"
os = "macos"

    [[assimp.download]]
    sha256 = "255b814d1d48e13ddfc7d66da71a810f63b4a4f15e1739619854e981e59bb35e"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.aarch64-apple-darwin.tar.gz"
[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "525ecd1545d10440e93627150e4a03b8f6124e99"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "0db8e46d3911ac8bbc510978b9fe92eeefd4795542e91953135e91e4973d705c"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.aarch64-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "61a3b36bbf0269ce8cda7b5d3554f8a8f75ca9e2"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "c97305044e3f54b83b9a1e1fec02de683bd08baf432e0273a2538d88c18005ab"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.aarch64-linux-musl-cxx11.tar.gz"
[[assimp]]
arch = "aarch64"
git-tree-sha1 = "0c04fb0f2a9481dbf1e12dc4f2bc9b4bf1e60fe9"
os = "freebsd"

    [[assimp.download]]
    sha256 = "779345ae0211173860d9d5e1d3b8263d28fe1aa2f14ee88a6fb0b4b677c9a453"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.aarch64-unknown-freebsd.tar.gz"
[[assimp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df3bec44cac8951b75a9c19fbbd79d6bde6d8fcf"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "0de41e78e8daad56f95fe8788d9e90287232ce17ce1d3206d9e81fb3b9f2558d"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[assimp]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d8aba275259fb8cf4e411cf4484194959d90ff5"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "c906374f475623295d8c79637bfccc5c8445a542309ab149693187964504f76f"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[assimp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a6432a14f1809fba4e2d970e4c8a04c0f7d49f9"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "0217ed2498efd1d493b51ee7e008b384d775ddb6aa4e11e80d2641421d0ec89e"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[assimp]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a7f8bc7c4c8c2f4e1addbc58acee31276192a7a"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "48558db86c213031636542ef02aa933a8c17051733f6dd8b9f0a1d3a8836c0a3"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8e4afe5108704dc2add00884457dee731b7c3cc"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "235090947f50128d657fac53b911a701bf05ebb9ccc1027c722568624d72bafa"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.i686-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "691256649182eaa80891f95168a7c03ef991e1c3"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "1e585ae363553532a261779b7893da78b1367a70ee24b9a069eee82765a54622"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.i686-linux-musl-cxx11.tar.gz"
[[assimp]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a5a04f10cfdc46bba9e4cad3338ee1db2ae88d0"
os = "windows"

    [[assimp.download]]
    sha256 = "e10cf5827467419cc306287358a12bd159dbec11476bb2a611fa1506bff2743b"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.i686-w64-mingw32-cxx11.tar.gz"
[[assimp]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cfde14ceeaf5e3f7c5a3a5b3bf32ef43cc15e10"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "1672727f856a2f9e2a2af00440bdc0edce702e617716cf1858ca6230ec258473"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d1698f50ef2a0cfa65decd6422a95bdf03d7961"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "7a94fd01aea9eac1379c857c7a476e474c6d9cca387f2bb331b93355b897db3e"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.riscv64-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
git-tree-sha1 = "e913a7f5177694185accb6b1e787d05092553dbd"
os = "macos"

    [[assimp.download]]
    sha256 = "f8794b0fa082d2a95e2369fec927fe931216f563f71ec2bc01743ea762094528"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.x86_64-apple-darwin.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d7286c8ec9b4240bd9a0e771214988bfef0e957"
libc = "glibc"
os = "linux"

    [[assimp.download]]
    sha256 = "105bfb82c144b47a8788ee6c630f79a28cf79e99df54b48c28e5f5b05c5174f9"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.x86_64-linux-gnu-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a49b8857a7ba4b935a6c30f012ee67e6ae11060"
libc = "musl"
os = "linux"

    [[assimp.download]]
    sha256 = "ffca743eeaa72fed9a6e960e3a24124dafb9347ca0c80644001b843bd61d6b54"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.x86_64-linux-musl-cxx11.tar.gz"
[[assimp]]
arch = "x86_64"
git-tree-sha1 = "b42a007bfff9a73fabdb403ce0bf7bbbb60d70f2"
os = "freebsd"

    [[assimp.download]]
    sha256 = "5036a7441033b890eb0c3b5cd5384b50344bc1a58ab01f4cf0ecefd0484bf5aa"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.x86_64-unknown-freebsd.tar.gz"
[[assimp]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebc8b865324029086e6e1cce2fe2df69457599b3"
os = "windows"

    [[assimp.download]]
    sha256 = "5fc19df6bc8ef1a2620d9a54f12af7b3872ca2bd7135c3dc9cbbb73bb9aac4b5"
    url = "https://github.com/JuliaBinaryWrappers/assimp_jll.jl/releases/download/assimp-v6.0.4+0/assimp.v6.0.4.x86_64-w64-mingw32-cxx11.tar.gz"
